use go docker image and binary tezos-client distribution

diff --git a/integration_test/Dockerfile b/integration_test/Dockerfile
--- a/integration_test/Dockerfile
+++ b/integration_test/Dockerfile
@@ -1,101 +1,19 @@
-ARG IMAGE=tezos/tezos:v9.7
-FROM ${IMAGE}
+FROM golang:1.16-alpine
+ARG TEZOS_CLIENT_VERSION=v9.7-1
 
-USER root
-
-RUN apk add --no-cache ca-certificates
-
-RUN [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' > /etc/nsswitch.conf
-
-ENV PATH /usr/local/go/bin:$PATH
-
-ARG GOLANG_VERSION=1.16.7
-
-RUN set -eux; \
-	apk add --no-cache --virtual .build-deps \
-		bash \
-		gcc \
-		gnupg \
-		go \
-		musl-dev \
-		openssl \
-	; \
-	apkArch="$(apk --print-arch)"; \
+RUN apkArch="$(apk --print-arch)" && \
 	case "$apkArch" in \
-		'x86_64') \
-			export GOARCH='amd64' GOOS='linux'; \
-			;; \
-		'armhf') \
-			export GOARCH='arm' GOARM='6' GOOS='linux'; \
-			;; \
-		'armv7') \
-			export GOARCH='arm' GOARM='7' GOOS='linux'; \
+		"x86_64") \
 			;; \
 		'aarch64') \
-			export GOARCH='arm64' GOOS='linux'; \
+			TEZOS_CLIENT_ARCH="-arm64" \
 			;; \
-		'x86') \
-			export GO386='softfloat' GOARCH='386' GOOS='linux'; \
+		*) echo >&2 "error: unsupported architecture '$apkArch'"; exit 1 \
 			;; \
-		'ppc64le') \
-			export GOARCH='ppc64le' GOOS='linux'; \
-			;; \
-		's390x') \
-			export GOARCH='s390x' GOOS='linux'; \
-			;; \
-		*) echo >&2 "error: unsupported architecture '$apkArch' (likely packaging update needed)"; exit 1 ;; \
-	esac; \
-	\
-# https://github.com/golang/go/issues/38536#issuecomment-616897960
-	url="https://dl.google.com/go/go${GOLANG_VERSION}.src.tar.gz"; \
-	\
-	wget -O go.tgz.asc "$url.asc"; \
-	wget -O go.tgz "$url"; \
-	\
-# https://github.com/golang/go/issues/14739#issuecomment-324767697
-	export GNUPGHOME="$(mktemp -d)"; \
-# https://www.google.com/linuxrepositories/
-	gpg --batch --keyserver keyserver.ubuntu.com --recv-keys 'EB4C 1BFD 4F04 2F6D DDCC EC91 7721 F63B D38B 4796'; \
-	gpg --batch --verify go.tgz.asc go.tgz; \
-	gpgconf --kill all; \
-	rm -rf "$GNUPGHOME" go.tgz.asc; \
-	\
-	tar -C /usr/local -xzf go.tgz; \
-	rm go.tgz; \
-	\
-	( \
-		cd /usr/local/go/src; \
-# set GOROOT_BOOTSTRAP + GOHOST* such that we can build Go successfully
-		export GOROOT_BOOTSTRAP="$(go env GOROOT)" GOHOSTOS="$GOOS" GOHOSTARCH="$GOARCH"; \
-		./make.bash; \
-	); \
-	\
-# pre-compile the standard library, just like the official binary release tarballs do
-	go install std; \
-# go install: -race is only supported on linux/amd64, linux/ppc64le, linux/arm64, freebsd/amd64, netbsd/amd64, darwin/amd64 and windows/amd64
-#	go install -race std; \
-	\
-	apk del --no-network .build-deps; \
-	\
-# remove a few intermediate / bootstrapping files the official binary release tarballs do not contain
-	rm -rf \
-		/usr/local/go/pkg/*/cmd \
-		/usr/local/go/pkg/bootstrap \
-		/usr/local/go/pkg/obj \
-		/usr/local/go/pkg/tool/*/api \
-		/usr/local/go/pkg/tool/*/go_bootstrap \
-		/usr/local/go/src/cmd/dist/dist \
-	; \
-	\
-	go version
+	esac && \
+	wget -O /usr/local/bin/tezos-client https://github.com/serokell/tezos-packaging/releases/download/${TEZOS_CLIENT_VERSION}/tezos-client${TEZOS_CLIENT_ARCH} && chmod a+x /usr/local/bin/tezos-client
+RUN apk add --no-cache linux-headers gcc musl-dev
 
-ENV GOPATH /go
-ENV PATH $GOPATH/bin:$PATH
-RUN mkdir -p "$GOPATH/src" "$GOPATH/bin" && chmod -R 777 "$GOPATH"
-
-# test part
-
-RUN apk add --no-cache linux-headers
 WORKDIR /app
 COPY . .
 RUN go mod download
